# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CoinApi' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CoinApi
    pod 'Alamofire'

  target 'CoinApiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CoinApiUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
